// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=cma, use-js-string=true, version=5.8.1

//# unitInfo: Provides: Weak_pointer
//# unitInfo: Requires: Core, Core__Heap_block, Expect_test_collector, Ppx_bench_lib__Benchmark_accumulator, Ppx_inline_test_lib__Runtime, Ppx_module_timer_runtime, Weak_array
(function
  (globalThis){
   "use strict";
   var
    runtime = globalThis.jsoo_runtime,
    cst_Weak_pointer = "Weak_pointer",
    cst_weak_pointer = "weak_pointer";
   function caml_call1(f, a0){
    return (f.l >= 0 ? f.l : f.l = f.length) == 1
            ? f(a0)
            : runtime.caml_call_gen(f, [a0]);
   }
   function caml_call2(f, a0, a1){
    return (f.l >= 0 ? f.l : f.l = f.length) == 2
            ? f(a0, a1)
            : runtime.caml_call_gen(f, [a0, a1]);
   }
   function caml_call3(f, a0, a1, a2){
    return (f.l >= 0 ? f.l : f.l = f.length) == 3
            ? f(a0, a1, a2)
            : runtime.caml_call_gen(f, [a0, a1, a2]);
   }
   var
    global_data = runtime.caml_get_global_data(),
    cst = "",
    Weak_array = global_data.Weak_array,
    Core_Heap_block = global_data.Core__Heap_block,
    Core = global_data.Core,
    Ppx_module_timer_runtime = global_data.Ppx_module_timer_runtime,
    Ppx_bench_lib_Benchmark_accumu =
      global_data.Ppx_bench_lib__Benchmark_accumulator,
    Expect_test_collector = global_data.Expect_test_collector,
    Ppx_inline_test_lib_Runtime = global_data.Ppx_inline_test_lib__Runtime;
   caml_call1(Ppx_module_timer_runtime[4], cst_Weak_pointer);
   caml_call1(Ppx_bench_lib_Benchmark_accumu[1][1], cst_weak_pointer);
   caml_call1(Expect_test_collector[5][1], "weak_pointer/src/weak_pointer.ml");
   caml_call2(Ppx_inline_test_lib_Runtime[2], cst_weak_pointer, cst);
   function create(param){return caml_call1(Weak_array[2], 1);}
   var index = 0;
   function get(t){return caml_call2(Weak_array[6], t, index);}
   function sexp_of_t(sexp_of_a, t){
    var x_001 = get(t), _a_ = caml_call1(Core_Heap_block[1], sexp_of_a);
    return caml_call2(Core[454], _a_, x_001);
   }
   function is_none(t){return caml_call2(Weak_array[8], t, index);}
   function is_some(t){return caml_call2(Weak_array[7], t, index);}
   function set(t, block){
    return caml_call3(Weak_array[4], t, index, [0, block]);
   }
   caml_call1(Ppx_inline_test_lib_Runtime[3], cst_weak_pointer);
   caml_call1(Expect_test_collector[5][2], 0);
   caml_call1(Ppx_bench_lib_Benchmark_accumu[1][2], 0);
   caml_call1(Ppx_module_timer_runtime[5], cst_Weak_pointer);
   var Weak_pointer = [0, sexp_of_t, create, get, is_some, is_none, set];
   runtime.caml_register_global(14, Weak_pointer, cst_Weak_pointer);
   return;
  }
  (globalThis));

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLjAsImZpbGUiOiJ3ZWFrX3BvaW50ZXIuY21hLmpzIiwic291cmNlUm9vdCI6IiIsIm5hbWVzIjpbImNyZWF0ZSIsImluZGV4IiwiZ2V0IiwidCIsInNleHBfb2ZfdCIsInNleHBfb2ZfYSIsInhfMDAxIiwiaXNfbm9uZSIsImlzX3NvbWUiLCJzZXQiLCJibG9jayJdLCJzb3VyY2VzIjpbIi9Vc2Vycy9qYWNvYnppZmYvLm9wYW0vZGl5LWhhemVsbnV0L2xpYi9jb3JlX2tlcm5lbC93ZWFrX3BvaW50ZXIvd2Vha19wb2ludGVyLm1sIl0sIm1hcHBpbmdzIjoiOzs7Ozs7Ozs7Ozs7Rzs7Ozs7Rzs7Ozs7Rzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7WUFNSUEsY0FBWSxPQUFBLDZCQUF3QjtPQUdwQ0M7WUFFQUMsSUFBSUMsR0FBSSxpQ0FBSkEsR0FGSkYsT0FFOEI7WUFFOUJHLFVBQVVDLFdBQVVGO0lBQVksSUFBUUcsUUFGeENKLElBRW9CQyx5Q0FBVkU7c0NBQThCQzs7WUFFeENDLFFBQVFKLEdBQUksaUNBQUpBLEdBTlJGLE9BTXNDO1lBQ3RDTyxRQUFRTCxHQUFJLGlDQUFKQSxHQVBSRixPQU9zQztZQUV0Q1EsSUFBSU4sR0FBRU87SUFBUSxPQUF1QiwwQkFBakNQLEdBVEpGLFdBU01TO0dBQTJDOzs7OzswQkFMakROLFdBUEFKLFFBS0FFLEtBS0FNLFNBREFELFNBR0FFOzs7RSIsInNvdXJjZXNDb250ZW50IjpbIigqIFdlIGltcGxlbWVudCBhIHdlYWsgcG9pbnRlciB1c2luZyBhIFtXZWFrX2FycmF5LnRdLiAqKVxuXG5vcGVuISBDb3JlXG5cbnR5cGUgJ2EgdCA9ICdhIFdlYWtfYXJyYXkudFxuXG5sZXQgY3JlYXRlICgpID0gV2Vha19hcnJheS5jcmVhdGUgfmxlbjoxXG5cbigqIFdlIHVzZSBhIHdlYWsgYXJyYXkgb2YgbGVuZ3RoIDEsIHNvIHRoZSB3ZWFrIHBvaW50ZXIgaXMgYXQgaW5kZXggMC4gKilcbmxldCBpbmRleCA9IDBcblxubGV0IGdldCB0ID0gV2Vha19hcnJheS5nZXQgdCBpbmRleFxuXG5sZXQgc2V4cF9vZl90IHNleHBfb2ZfYSB0ID0gWyVzZXhwIChnZXQgdCA6IGEgSGVhcF9ibG9jay50IG9wdGlvbildXG5cbmxldCBpc19ub25lIHQgPSBXZWFrX2FycmF5LmlzX25vbmUgdCBpbmRleFxubGV0IGlzX3NvbWUgdCA9IFdlYWtfYXJyYXkuaXNfc29tZSB0IGluZGV4XG5cbmxldCBzZXQgdCBibG9jayA9IFdlYWtfYXJyYXkuc2V0IHQgaW5kZXggKFNvbWUgYmxvY2spXG4iXX0=
